name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: ðŸ“‡ Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.7.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: ðŸ‘Œ Approve Dependabot PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: ðŸ”€ Enable auto-merge for Dependabot PRs
        # if: |
        #   (steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor' ||
        #    steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch')
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
